export type Block =
  | { t: "p"; x: string }
  | { t: "h2"; x: string }
  | { t: "quote"; x: string }
  | { t: "list"; x: string[] };

export type Post = {
  slug: string;
  title: string;
  dek: string;
  category: string;
  date: string;
  readTime: string;
  author: string;
  role: string;
  image: string;
  featured?: boolean;
  body: Block[];
};

export const categories = [
  "All",
  "Music Industry",
  "Artist Growth",
  "Release Strategy",
  "Marketing",
  "Production",
  "Distribution",
  "Artist Stories",
  "Social Impression Insights",
];

export const posts: Post[] = [
  {
    slug: "death-of-the-demo-dump",
    title: "The Death of the Demo Dump",
    dek: "You have 14 voice memos and zero releases. Here is why the vault is killing your career — and the rule that fixes it.",
    category: "Release Strategy",
    date: "Aug 18, 2026",
    readTime: "6 min read",
    author: "Dev Malhotra",
    role: "Head of Release Strategy",
    image: "https://images.unsplash.com/photo-1487180144351-b8472da7d491?q=80&w=1600&auto=format&fit=crop",
    featured: true,
    body: [
      { t: "p", x: "Every artist we onboard arrives with the same secret: a folder of almost-finished songs. Fourteen voice memos. Six rough mixes. One track that is 'basically done, just needs vocals, mixing, mastering, artwork and a reason to exist.' We call it the demo dump, and it feels productive. It is the opposite." },
      { t: "p", x: "A demo dump is a museum of decisions you refused to make. Every unfinished song is a song that cannot be streamed, pitched, synced, or played by a stranger. It has no metadata, no release date, no chance. The vault does not protect your music. It buries it." },
      { t: "h2", x: "Why we hoard" },
      { t: "p", x: "Hoarding feels safe because an unreleased song can never fail. The moment a song is out, it has numbers attached to it — streams, saves, skips. Numbers feel like verdicts. So we keep polishing, keep starting new songs, keep the fantasy alive that the next one will be the one we finally ship perfectly." },
      { t: "quote", x: "An unreleased song can't fail. That's exactly why it can't win." },
      { t: "p", x: "But here is what actually happens when you release: you learn. The market gives you data no amount of bedroom polishing can. Which hook people screenshot. Where they skip. Which city saves your song at 2 AM. That feedback is the real producer of your next song." },
      { t: "h2", x: "The 3-song rule" },
      { t: "p", x: "When an artist joins Social Impression, the first thing we do in song grooming is brutal triage. Pick three. One that is closest to done. One that is the most 'you.' One that scares you a little. Everything else goes back in the vault — deliberately, without guilt." },
      { t: "list", x: ["Closest to done: ship it first. Momentum beats perfection.", "Most 'you': this is your identity anchor. Every release should rhyme with it.", "Scary one: growth lives here. Give it a real budget and a real date."] },
      { t: "p", x: "Three songs is a strategy. Fourteen is anxiety with a file structure. The artists who grow are not the ones with the biggest vaults — they are the ones who decide, ship, learn, and decide again." },
      { t: "p", x: "So open the folder. Pick one. Give it a date before you give it another plugin. The demo dump dies the day your first single goes live." },
    ],
  },
  {
    slug: "how-the-algorithm-discovers-you",
    title: "How the Algorithm Actually Discovers You",
    dek: "Forget hacks. Here is the unglamorous machine that decides whether your song gets heard — and the three signals you can actually control.",
    category: "Marketing",
    date: "Aug 11, 2026",
    readTime: "7 min read",
    author: "Sana Kapoor",
    role: "Marketing Lead",
    image: "https://images.unsplash.com/photo-1461784121038-f088ca1e7714?q=80&w=1600&auto=format&fit=crop",
    body: [
      { t: "p", x: "Artists talk about 'the algorithm' like it is a bouncer with personal grudges. It is not. It is a recommendation engine with a simple job: find listeners who will finish, save, and come back. It has no taste, no mood, and no opinion about your outfit. It has signals. Thousands of them. But three matter more than the rest." },
      { t: "h2", x: "Signal 1: Completion rate" },
      { t: "p", x: "Do people finish your song? Not skip after 20 seconds? This is why song grooming exists. If your intro is 45 seconds of atmosphere, the algorithm never sees the hook, because the listener is already gone. We cut one artist's intro from 40 seconds to 8. Same song. Skip rate halved. Nothing else changed." },
      { t: "h2", x: "Signal 2: Save-to-stream ratio" },
      { t: "p", x: "A save is a promise of a future stream. Platforms weight it heavily because it predicts habit, not hype. You cannot fake it, but you can earn it: make the chorus arrive early, make the title worth remembering, and put the pre-save link where the excitement actually happens — not three weeks before, when nobody cares yet." },
      { t: "h2", x: "Signal 3: Listener-to-artist conversion" },
      { t: "p", x: "When one person queues three of your songs in a row, the platform starts showing you to strangers who like what that listener likes. This is why consistency beats one viral moment. Two good releases in 90 days teach the machine who your audience is. One release every 14 months teaches it nothing." },
      { t: "quote", x: "The algorithm is not against you. It is just waiting for a pattern." },
      { t: "list", x: ["Front-load your hook. Respect the 20-second test.", "Ask for the save, not the follow. Saves compound.", "Release again within 90 days. Patterns are made of repetition."] },
      { t: "p", x: "None of this is a hack. It is just respecting how the machine listens. The artists who grow are rarely the loudest — they are the most legible." },
    ],
  },
  {
    slug: "first-studio-session",
    title: "Your First Studio Session: What Nobody Tells You",
    dek: "The engineer is not judging you. The red light is not the enemy. A field guide to not wasting the most expensive hours of your year.",
    category: "Production",
    date: "Aug 4, 2026",
    readTime: "5 min read",
    author: "Rhea D'Souza",
    role: "Head of Production",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1600&auto=format&fit=crop",
    body: [
      { t: "p", x: "Studio time is the only purchase in music where nerves can physically eat your money. You book four hours, the clock starts, and suddenly your voice forgets every melody you have sung in the shower for two years. Here is what experienced artists do differently." },
      { t: "h2", x: "The session starts the night before" },
      { t: "p", x: "Hydrate. Sleep. No shouty bars the night before. Bring the lyric sheet printed — phone screens die at the worst moment. And rehearse the song at 90% energy, not 110%. Over-singing is the most common first-session mistake; the mic is closer than your bedroom wall." },
      { t: "h2", x: "Tell the engineer your references" },
      { t: "p", x: "'Make it sound expensive' is not a direction. 'The vocals should sit close and dry, like the second verse of this song' is. Two reference tracks, sent before the session, save an hour of guessing. This is exactly why our intake asks for references before production ever starts." },
      { t: "quote", x: "The red light is not a test. It is a tool that only works if you keep singing." },
      { t: "h2", x: "Comp as you go" },
      { t: "p", x: "Do not record 30 takes and hope one is magic. Sing three solid takes, comp the best phrases, then punch in the weak lines while the emotion is still warm. Artists who comp as they go leave with a vocal. Artists who marathon-take leave with fatigue and a bill." },
      { t: "list", x: ["Warm up 15 minutes before, not during.", "Keep the hook takes for last — energy matters most there.", "Listen back once at conversation volume, then commit.", "Drink water at room temperature. Cold tightens cords."] },
      { t: "p", x: "One more thing nobody says out loud: you are allowed to say a take is good. Perfectionism in the vocal booth is just fear wearing headphones. Ship the take that moves you." },
    ],
  },
  {
    slug: "streaming-payouts-explained",
    title: "Streaming Payouts, Explained Like You're an Artist, Not an Accountant",
    dek: "Where the money actually goes between a listener's play and your bank account — and the two mistakes that quietly cost artists thousands.",
    category: "Music Industry",
    date: "Jul 28, 2026",
    readTime: "8 min read",
    author: "Dev Malhotra",
    role: "Head of Release Strategy",
    image: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?q=80&w=1600&auto=format&fit=crop",
    body: [
      { t: "p", x: "You have seen the number: roughly ₹0.10–0.30 per stream in India, depending on the platform and the listener's plan. The number everyone argues about. The number almost nobody traces. So let's trace it." },
      { t: "h2", x: "The journey of one stream" },
      { t: "p", x: "A listener plays your song. The platform pools that month's subscription and ad revenue, keeps its cut, and divides the rest by total streams to get a per-play rate. That rate goes to the distributor, who takes their fee, and passes the rest to whoever owns the recording — that should be you. Separately, the composition (the lyrics and melody) earns publishing royalties that flow through societies like IPRS. Two pipelines. Most artists only know about one." },
      { t: "quote", x: "Most 'streaming doesn't pay' conversations are really 'I never registered my publishing' conversations." },
      { t: "h2", x: "Mistake 1: Unclaimed publishing" },
      { t: "p", x: "If you wrote the song and never registered with a collection society, the composition royalties for your streams are sitting in black boxes, distributed to people who did register. Registration takes an afternoon. We walk every Social Impression artist through it during onboarding, because a release without publishing setup is a tap running into someone else's bucket." },
      { t: "h2", x: "Mistake 2: Splits agreed in DMs" },
      { t: "p", x: "A producer said 'we'll figure it out later.' A feature said 'just credit me.' Six months later the song earns, and 'later' becomes an argument. Splits must be written before release — even a simple signed message listing percentages beats memory. Your future collaborators will respect you more, not less." },
      { t: "list", x: ["Register with your collection society the week you release.", "Write splits down before the song goes live, not after it charts.", "Check your distributor's statement monthly — errors compound quietly.", "Treat ₹0.20 per stream as marketing data, not income. Volume is the business model."] },
      { t: "p", x: "Streaming will not make you rich at 10,000 streams. But understood properly, it is a feedback engine: every rupee and every play tells you where to point next. Artists who read their data get richer in every sense. Artists who don't, blame the number." },
    ],
  },
  {
    slug: "48-hour-release-playbook",
    title: "The 48-Hour Release Week Playbook",
    dek: "Release day is not a date, it's a campaign. The exact sequence we run for every Social Impression release — hour by hour.",
    category: "Release Strategy",
    date: "Jul 21, 2026",
    readTime: "7 min read",
    author: "Sana Kapoor",
    role: "Marketing Lead",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1600&auto=format&fit=crop",
    body: [
      { t: "p", x: "Most artists treat release day like a birthday: it arrives, people say congrats, and by the weekend everything is normal again. But release week is not a celebration — it is the highest-leverage 48 hours of your quarter. Platforms are watching the early numbers. Playlists are watching the platforms. Here is the sequence we run." },
      { t: "h2", x: "T-minus 24 hours" },
      { t: "p", x: "Post the 'it's almost here' story with the pre-save link and a 15-second teaser of the hook — not the intro, the hook. Message your 20 closest supporters personally. Not a broadcast list; actual messages. Early saves from real accounts are rocket fuel for Release Radar." },
      { t: "h2", x: "Hour zero" },
      { t: "p", x: "The link goes out everywhere simultaneously: feed post, story, WhatsApp status, community servers. Pin a comment with the streaming link. Reply to every single comment in the first two hours — engagement velocity in hour one matters more than total engagement by Friday." },
      { t: "quote", x: "The first 72 hours don't just reflect your release. They program its next 90 days." },
      { t: "h2", x: "Hour 12 to 48" },
      { t: "list", x: ["Post the 'out now' reel with a visual hook in the first second.", "Share a behind-the-song story: what it's about, in your own words.", "Thank early supporters publicly — screenshotted saves are social proof.", "Submit the song to playlist curators who accepted your pitch wave.", "Watch the dashboard: if a city is over-indexing, geo-target an ad there the same day."] },
      { t: "p", x: "Notice what is missing: begging for streams, engagement pods, 'support my music' spam. Those burn trust with the audience and signals with the platform. The playbook is not magic — it is just sequence, speed, and sincerity. Release week rewards the prepared." },
    ],
  },
  {
    slug: "second-single-matters-more",
    title: "Why Your Second Single Matters More Than Your First",
    dek: "The debut proves you exist. The follow-up proves you're a career. Nobody plans for it — and that's why most artists disappear after their first drop.",
    category: "Artist Growth",
    date: "Jul 14, 2026",
    readTime: "6 min read",
    author: "Dev Malhotra",
    role: "Head of Release Strategy",
    image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?q=80&w=1600&auto=format&fit=crop",
    body: [
      { t: "p", x: "There is a strange graveyard in independent music: artists with one great song and 40,000 monthly listeners who vanish within a year. Not because the first release failed — because the second one was never really planned. The debut got the year of attention. The follow-up got six weeks and a shrug." },
      { t: "h2", x: "The first single is a promise" },
      { t: "p", x: "A debut says: this is who I am. It earns you strangers' attention, your first playlist adds, your first press reply. It is allowed to be a moment. But a moment is all it is. Every curator, editor and algorithm treats a debut as an experiment until proven otherwise." },
      { t: "h2", x: "The second single is a pattern" },
      { t: "p", x: "The follow-up says: this was not luck. When your second release rhymes with your first — sonically, visually, in tone — the audience that saved song one hears song two and thinks: this is a thing now. That is the moment passive listeners become fans. It is also the moment editorial curators move you from 'watchlist' to 'artist.'" },
      { t: "quote", x: "One song is a coincidence. Two is a genre. Three is a career." },
      { t: "h2", x: "Plan the second before releasing the first" },
      { t: "list", x: ["Write the second single while mixing the first — momentum is a creative resource.", "Keep 70% sonic continuity. Surprise people on purpose, not accidentally.", "Leave data threads: end song one in a way that makes people check your profile.", "Budget for the follow-up's marketing before the debut's, not after."] },
      { t: "p", x: "This is why Momentum exists as a package and not just a vibe: two releases inside 90 days, planned as one arc. The debut opens the door. The second single teaches the world to walk through it." },
    ],
  },
  {
    slug: "asen-momentum-story",
    title: "From Bedroom to Broadcast: How ASEN Found His Frequency",
    dek: "A Delhi rapper, a song he'd given up on, and 60 days that moved him from open mics to sold-out basements.",
    category: "Artist Stories",
    date: "Jul 7, 2026",
    readTime: "5 min read",
    author: "Social Impression",
    role: "Editorial",
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=1600&auto=format&fit=crop",
    body: [
      { t: "p", x: "Aarav Sen almost didn't submit the song. 'Static/Signal' had been rejected — politely — by two producers and one very impolite Reddit thread. It was too fast, too talky, too Delhi. When he joined the Social Impression waitlist, he listed it last on his own song list, like an apology." },
      { t: "h2", x: "Grooming, not surgery" },
      { t: "p", x: "In pre-production, his producer did something unexpected: she changed almost nothing structural. Instead she cut 11 seconds of intro, doubled the hook into a call-and-response, and re-voiced the second verse's ad-libs. 'The song wasn't broken,' she said. 'It was wearing the wrong clothes.'" },
      { t: "quote", x: "Same chords, same words — completely different life. It found playlists I'd been cold-DMing for a year." },
      { t: "h2", x: "Sixty days, one arc" },
      { t: "p", x: "The Momentum rollout treated release week as a beginning, not an event. Teaser clips led with the hook. The visualiser dropped 48 hours after the audio, giving the algorithm a second ignition. Playlist pitching targeted 14 lists — 12 said yes, including two editorial ones. By day 40, 'Static/Signal' had crossed a million streams, and Aarav's monthly listeners had grown 9x." },
      { t: "list", x: ["12 editorial playlist adds in 60 days", "1.4M streams and counting on the lead single", "First sold-out show: 220-cap basement, Delhi", "Follow-up single already in production"] },
      { t: "p", x: "Asked what changed, Aarav thinks for a second. 'I stopped sending links and started building a catalogue. The team didn't make me a different artist. They made me audible.' His next single is called 'Blue Tick.' Given the trajectory, it won't need one." },
    ],
  },
  {
    slug: "inside-a-grooming-session",
    title: "Inside a Social Impression Grooming Session",
    dek: "No, it's not a haircut. The 90-minute ritual where a song either finds its spine or gets sent back to the vault.",
    category: "Social Impression Insights",
    date: "Jun 30, 2026",
    readTime: "6 min read",
    author: "Rhea D'Souza",
    role: "Head of Production",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=1600&auto=format&fit=crop",
    body: [
      { t: "p", x: "Before any Social Impression song gets produced, it goes through grooming — a structured session where we interrogate the song until it either stands taller or admits it wasn't ready. Artists are often nervous about this meeting. They shouldn't be. It is the highest-ROI hour of the whole journey. Here is exactly what happens." },
      { t: "h2", x: "Minute 0–15: The naked listen" },
      { t: "p", x: "We play the demo on one speaker, phone-level volume. No headphones, no studio magic. If the song survives at phone quality, the songwriting is real. If it collapses, we've found the truth early: it was arrangement doing the work of melody, and arrangement can't save it on a playlist sandwiched between giants." },
      { t: "h2", x: "Minute 15–45: The interrogation" },
      { t: "list", x: ["What is this song actually about — in one sentence, no adjectives?", "Where does a first-time listener feel something? Timestamp it.", "Which section would you defend with your life? That's your anchor.", "What are you hiding behind — length, layers, loudness?"] },
      { t: "quote", x: "We're not looking for a better song. We're looking for your song, with everything that isn't it removed." },
      { t: "h2", x: "Minute 45–90: The rebuild plan" },
      { t: "p", x: "We leave with a one-page song map: the anchor, the hook's arrival time, the arrangement's job list, key and tempo decisions, and two reference tracks. This document goes into the artist's dashboard, and production is measured against it. No vibes-based production. No twelve-version drift. The song gets a spine, and everyone — artist, producer, engineer — builds around the same one." },
      { t: "p", x: "Some songs don't survive grooming. That's a feature: better to learn a song isn't ready in a meeting than in a market. The ones that do survive enter production knowing exactly what they are. That confidence is audible." },
    ],
  },
  {
    slug: "distribution-is-not-a-vending-machine",
    title: "Distribution Is Not a Vending Machine",
    dek: "Uploading a song is free now. So why do releases still fail? Because delivery was never the hard part.",
    category: "Distribution",
    date: "Jun 23, 2026",
    readTime: "5 min read",
    author: "Dev Malhotra",
    role: "Head of Release Strategy",
    image: "https://images.unsplash.com/photo-1501612780327-45045538702b?q=80&w=1600&auto=format&fit=crop",
    body: [
      { t: "p", x: "Anyone can put a song on Spotify for the price of a coffee. This is genuinely wonderful. It is also why 'we distribute your music' stopped being a value proposition years ago — and why so many independent releases still arrive stillborn. Distribution was never about the upload. It is about everything the upload triggers." },
      { t: "h2", x: "The metadata is the product" },
      { t: "p", x: "Wrong artist spelling, missing ISRC, a featured artist in the primary artist field, artwork with a border that violates spec — each of these is a small bomb planted in your release. Some delay you. Some split your royalties. Some quietly create a second artist profile that fragments your audience forever. Clean metadata is not admin. It is identity management." },
      { t: "h2", x: "The date is a strategy" },
      { t: "p", x: "Platforms index new releases weekly. Editorial pitching windows close 3–4 weeks before release. Pre-save campaigns need runway. A song delivered 'whenever' forfeits every one of those systems. A locked date — respected by a whole team — turns the same upload into a coordinated landing." },
      { t: "quote", x: "A distributor moves files. An ecosystem moves releases." },
      { t: "list", x: ["Pitch to editorial at least 3 weeks out, every release.", "Claim Spotify for Artists and Apple for Artists before go-live, not after.", "Keep one artist name, spelled identically, everywhere, forever.", "Deliver 2+ weeks early. Review queues are weather, not schedules."] },
      { t: "p", x: "So yes, the vending machine exists, and it's cheap. But a release is not a file. It is a date, a metadata set, a pitch, a profile, a pre-save, and a plan. That is what the 'free' button doesn't do — and what an ecosystem is for." },
    ],
  },
];
